group 'com.jhomlala.better_player.better_player'
version '1.0-SNAPSHOT'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22"
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 34
    namespace "com.jhomlala.better_player"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"
    }

    dependencies {
        implementation "com.google.android.exoplayer:exoplayer-core:2.18.1"
        implementation "com.google.android.exoplayer:exoplayer-hls:2.18.1"
        implementation "com.google.android.exoplayer:exoplayer-dash:2.18.1"
        implementation "com.google.android.exoplayer:exoplayer-smoothstreaming:2.18.1"
        implementation "com.google.android.exoplayer:exoplayer-ui:2.18.1"
        implementation "com.google.android.exoplayer:extension-mediasession:2.18.1"
        implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.6.0-alpha02"
        implementation "androidx.lifecycle:lifecycle-common:2.6.0-alpha02"
        implementation "androidx.lifecycle:lifecycle-common-java8:2.6.0-alpha02"
        implementation "androidx.annotation:annotation:1.4.0"
        implementation "androidx.work:work-runtime:2.7.1"
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.22"
}
